ERROR 2022-07-15 22:03:33,748 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:34,696 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:35,678 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:36,620 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:37,531 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:38,422 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:39,358 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:40,250 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:41,126 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:42,046 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:43,052 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:43,989 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:44,926 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:45,849 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:46,777 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:47,677 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:48,606 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:49,584 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:50,583 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 22:03:51,573 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 686, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
