ERROR 2022-07-15 21:50:02,124 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 678, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 21:50:03,115 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 678, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 21:50:04,069 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 678, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 21:50:05,036 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 678, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
ERROR 2022-07-15 21:50:06,006 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 678, in mainWork
    if self.checkBox.isChecked():
AttributeError: 'runBatchcommand' object has no attribute 'checkBox'
